const products = [
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'beds',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'plants',
        name: 'une plante verte',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'electronics',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'sofas',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'lamps',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
    {
        type: 'wall-decor',
        name: 'La chambre à toto',
        model: 'xxx_tata',
        price: 50,
        image: 'https://via.placeholder.com/800x800',
    },
];


export default products;